sudo: required
services:
  - docker

script:
  - docker build -t alzobaydee/node .  #<dockeruser/nameofproject>
  - docker images alzobaydee/node    #<dockeruser/nameofproject>

before_deploy:
  - docker login -u alzobaydee -p FLAmenco19888    # -u <username>  -p <userpassword>

deploy:
  provider: script
  script: docker push alzobaydee/node   #<dockeruser/nameofproject>
  on:
    branch: master
