sudo: required
services:
  - docker

script:
  - docker build -t alzobaydee/node
  - docker images alzobaydee/node

before_deploy:
  - docker login -u alzobaydee -p FLAmenco19888 

deploy:
  provider: script
  script: docker push alzobadydee/node
  on:
    branch: master